config/routes.rb
Refectory::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users" }
  devise_scope :user do
    get 'login', to: "devise/sessions#new", as: "login"
    get 'logout', to: "devise/sessions#destroy", as: "logout"
    get 'logout', to: "users/sessions#destroy", as: "logout"
    get 'signup', to: "users#new", as: "signup"
    # match '/users/:id', :to => 'users#show', :as => :user
  end
  root :to => 'tutorials#index'
 
devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' 
get 'users/:id' => 'users#show'
end
  resources :users
  resources :tutorials
  resources :comments, only: [:show, :create, :update, :destroy]
 
 resources :tutorials do
    member { post :vote }
  end

  if Rails.env == "development"
    match 'errors/404' => 'errors#error_404'
    match 'errors/500' => 'errors#error_500' 
  end
  
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

  match 'tagged' => 'tutorials#tagged', :as => 'tagged'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :profile_attributes

  has_one :profile
  accepts_nested_attributes_for :profile
  
 
  has_many :tutorials
  has_many :comments
  
has_reputation :user_votes, source: {reputation: :votes, of: :tutorials}, aggregated_by: :sum

  
  def admin?
    self.email == "andrew@atevans.com" || self.email == "danvoell@gmail.com"
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

def show
  @user = User.find(params[:id])
  @tutorials = @user.tutorials
  # raise @user.inspect
  @search = params[:search]  
   @tutorials = Tutorial.search(@search) 

end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= devise_error_messages! %>

  <%= f.label :email %>
  <%= f.email_field :email %>

   <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password, :autocomplete => "off" %>
  <span class="help-block">(leave blank if you don't want to change it)</span>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :current_password %>
  <%= f.password_field :current_password %>
  <span class="help-block">(we need your current password to confirm your changes)</span>

  <div class="actions">
    <%= f.submit "Update", :class => "btn" %>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete %>.</p>

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<%= @user.all %>

<li><%= link_to "Profile", @user %></li>
<li><%= link_to "Settings", edit_user_registration_path %></li>
<li><%= link_to "Logout", destroy_user_session_path, method: "delete" %></li>

app/views/users/new.html.erb
<div class="row">
	</div>

<div class="row">
<div class="span6">
<h1 class="heading">Make and complete tutorials, together.</h1>
<p class="subheading">Learn to code by following step-by-step software tutorials. Comment on individual steps. Build tutorials on top of each other to create complex applications.</p>
<hr><p class="subheading"><b>1,270</b> tutorials successfully completed!</p>
</div>
<div class="span6">

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <%= f.label :email %>
  <%= f.email_field :email %>

 <%= f.label :username %>
  <%= f.text_field :username %>
  
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <div class="actions">
	
   <%= f.submit "Sign up for free", :class => "btn btn-success btn-large" %>
  </div>
<% end %>


<%= render "devise/shared/links" %>
</div>
</div>
<hr>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<!-- <h5><%= @user.tutorials %></h5> -->
<p> This user has authored <%= @user.tutorials.count %> tutorials!</p>


<ul>
<% @tutorials.each do |tutorial| %>
  <li><%= link_to tutorial.title, tutorial_path(tutorial) %></li>
<% end %>
</ul>