config/routes.rb
Refectory::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users" }
  devise_scope :user do
    get 'login', to: "devise/sessions#new", as: "login"
    get 'logout', to: "devise/sessions#destroy", as: "logout"
    get 'logout', to: "users/sessions#destroy", as: "logout"
    get 'signup', to: "users#new", as: "signup"
    # match '/users/:id', :to => 'users#show', :as => :user
  end
  root :to => 'tutorials#index'
 
devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' 
get 'users/:id' => 'users#show'
end
  resources :users
  resources :tutorials
  resources :comments, only: [:show, :create, :update, :destroy]
 
 resources :tutorials do
    member { post :vote }
  end

  if Rails.env == "development"
    match 'errors/404' => 'errors#error_404'
    match 'errors/500' => 'errors#error_500' 
  end
  
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

  match 'tagged' => 'tutorials#tagged', :as => 'tagged'
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base


  belongs_to :user
  has_many :steps
  has_many :comments
  
  attr_accessible :name, :image, :remote_image_url, :title, :tag_list, :outline, :file, :thumb, :website, :steptitle
   mount_uploader :image, ImageUploader
  
  acts_as_taggable
  
has_reputation :votes, source: :user, aggregated_by: :sum

  def editor?(edit_user)
    self.user_id == edit_user.id || edit_user.admin?
  end

  def to_param
  	"#{id}-#{title}".parameterize
  end

def tagged
  if params[:tag].present? 
    @tutorials = Tutorial.tagged_with(params[:tag])
  else 
    @tutorials = Tutorial.postall
  end  
end


def self.search(search)
  if search
    find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end

end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :tagged]
  before_filter :find_tutorial, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_tutorial, only: [:edit, :update, :destroy]
  
  def index
    @tutorials = Tutorial.all
    @search = params[:search]  
    @searchtutorials = Tutorial.search(@search)  
    # @tutorials = Tutorial.search(params[:search])
    @tutorials = Tutorial.paginate(:page => params[:page], :per_page => 8, :order => 'id DESC')
end

def search
  @tutorials = Tutorial.search params[:search]
end
  
  def show
    @tutorial = Tutorial.find(params[:id])
  end
  
  def new
    @tutorial = Tutorial.new
    @search = params[:search]  
    @tutorials = Tutorial.search(@search) 
  end
  
def tagged
  if params[:tag].present? 
    @tutorials = Tutorial.tagged_with(params[:tag])
  else 
    @tutorials = Tutorial.postall
  end  
end

def vote
  value = params[:type] == "up" ? 1 : -1
  @tutorial = Tutorial.find(params[:id])
  @tutorial.add_or_update_evaluation(:votes, value, current_user)
  redirect_to :back, notice: "Congratulations, you did it! Please spread the word about your momentous achievement to your social stratosphere. We are a free tool and don't have a marketing budget, each share might help another developer in training get unstuck."
end


  def create
    @tutorial = Tutorial.new(params[:tutorial])
    @tutorial.user = current_user
    if @tutorial.save
      redirect_to edit_tutorial_path(@tutorial), notice: "Tutorial created!"
    else
      flash.now[:alert] = "Oops, there was a problem: #{@tutorial.all_errors}"
      render :new
    end
  end
  
  def edit
    @tutorial.steps.build(content: "")
  end
  
  def update
    @tutorial.steps.destroy_all
    steps = params[:tutorial].delete(:step) || []
    steps = steps.to_a.collect{|k, v| v }.compact if steps.present?
    steps.each do |step|
      next if step['content'].empty?
      @tutorial.steps.create(step)
    end
    
    if @tutorial.update_attributes(params[:tutorial])
      
      redirect_to edit_tutorial_path(@tutorial), notice: "Tutorial saved!"
    else
      flash.now[:alert] = "Oops, there was a problem: #{@tutorial.all_errors}"
      render :edit
    end
  end
  
  def destroy
    @tutorial.destroy
    redirect_to tutorials_path, notice: "Tutorial deleted."
  end

  
  private
    def find_tutorial
      @tutorial = Tutorial.find_by_id(params[:id])
      redirect_to tutorials_path, alert: "Couldn't find that tutorial" unless @tutorial.present?
    end
    
    def authenticate_tutorial
      redirect_to tutorials_path, alert: "You don't have permission to do that" unless @tutorial.editor?(current_user)
    end
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/_comment.html.erb
<div class="well">
  <%= mail_to comment.user.username %> says:
  <blockquote><%= comment.content.html_safe %></blockquote>
  <% if current_user.present? && comment.editor?(current_user) %>
    <div class="actions">
      <%= link_to "Delete", comment_path(comment), :method => "delete", :confirm => "Are you sure?", :class => "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/tutorials/_comment_form.html.erb
<% comment = comment_form %>
<% comment ||= @comment %>
<%= form_for comment do |f| %>
  <% that = comment.tutorial_id.present? ? "tutorial" : "step" %>
  <%= f.hidden_field :tutorial_id %>
  <%= f.hidden_field :step_id %>
  
  <%= f.label :content, "Post a comment on this #{that}:" %>
  <%= f.text_area :content, :size => "50x2", :class => 'wysihtml5-comment span5' %>
  <br />
  <%= f.button "Save", :class => "btn" %>
<% end %>

app/views/tutorials/_form.html.erb
<% tutorial = form %>
<% tutorial ||= @tutorial %>

<%= form_for tutorial do |f| %>


 
  <%= f.text_field :title, :class => "span4", :placeholder => "Tutorial Title" %><br>
 <!--Add an image of what the finished tutorial will look like: <%= f.file_field :image %> -->  <%= f.text_field :website, :class => "span4", :placeholder => "Link to Working Demo or Website" %>

<div class="row">
    <div class="span4">
      <%= f.label :tags, "Tags (Comma, Seperated):" %>
      <%= f.text_field :tag_list, value: @tutorial.tags.collect(&:name).join(", "), class: "tagit" %>
    </div>
  </div>
  
  <%= f.label :outline, "Short Overview of Tutorial:" %>
  <%= f.text_area :outline, :size => "75x5", :class => "span8 wysihtml5" %>
  <br />
  <%= f.button "Submit To Start Adding Steps", :class => "btn" %>
<% end %>

app/views/tutorials/edit.html.erb
<h1><%= @tutorial.title %></h1>
<%= form_for @tutorial do |f| %>
  <div class="row">
    <div class="span12">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "span6" %>
      
      <div class="row">
        <div class="span8">
          <%= f.label :tags %>
          <%= f.text_field :tag_list, value: @tutorial.tags.collect(&:name).join(", "), placeholder: "ruby, solr, sunspot", class: "tagit" %>
          <span class="help-block">
            Separate by commas, use double quotes for multi-word tags
          </span>
        </div>
      </div>
    
      <%= f.label :outline %>
      <%= f.text_area :outline, :size => "75x5", :class => "span8 wysihtml5" %>
    </div>
  </div>
  
  <h3>Tutorial Steps:</h3>
  <div class="accordion" id="steps-accordion">
    
    <% count = 0 %>
    <% @tutorial.steps.each do |step| %>
    
      <% count += 1 %>
      <div class="accordion-group" data-kind="step" data-step-count="<%= count %>">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#steps-accordion" href="#step-<%= step.id %>">
            Step <%= count %> - <%= step.steptitle %>
          </a>
        </div>
      
        <div id="step-<%= step.id %>" class="accordion-body collapse <%= count == 1 ? 'in' : '' %>">
          <div class="accordion-inner">
            <%= f.fields_for step, index: (step.id || 'new') do |s| %>
               <%= s.text_field :steptitle, :placeholder => "Step Title (Create Rails App...)" %>
              <%= s.text_area :content, :size => "75x10", :class => "span8 wysihtml5" %>

            <% end %>
            <br />
            <a href='#' class="btn btn-danger remove-step" data-kind="remove-step">Remove Step</a>
            <div class='clearfix'>&nbsp;</div>
          </div>
        </div>
      </div>
    <% end %>
      
  </div>
  
  <!-- <a href='#' class="btn" data-kind="new-step">Add Step</a> -->
  
  <div class="hide" data-kind="new-step">
    <div class="accordion-group" data-kind="step">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#steps-accordion" href="#step-new-step-id">
          Step :count:
        </a>
      </div>
    
      <div id="step-new-step-id" class="accordion-body collapse">
        <div class="accordion-inner">
          <%= f.fields_for Step.new, index: 'new-step-id' do |s| %>
            <%= s.text_area :content, :size => "75x10", :class => "span8" %>
          <% end %>
          <br />
          <a href='#' class="btn btn-danger remove-step" data-kind="remove-step">Remove Step</a>
          <div class='clearfix'>&nbsp;</div>
        </div>
      </div>
    </div>
  </div>
  
  <hr />
  <%= f.button "Save To Finish Or Add New Step", :class => 'btn btn-large' %>
<% end %>

<br />
<%= link_to "Back", tutorials_path %>

app/views/tutorials/index.html.erb
     
<div class="row">
  <div class="span9">
<table class="table table-striped">


  

<% @tutorials.each do |tutorial| %>

    <tr>

  

<!--<td><%= image_tag tutorial.image_url(:thumb) if tutorial.image? %></td>      -->

<div class="details">
<td>

  <ul class="fa-ul">
  <li><i class="fa-li fa fa-thumbs-up"></i><%= tutorial.reputation_for(:votes).to_i %></li>
</ul>


<td>
  <h3><%= link_to truncate(tutorial.title, length: 65), tutorial_path(tutorial) %>

</h3>
</div>
<div class="shortdescription"><%= raw(truncate(tutorial.outline.html_safe, length: 200)) %></div>
<div class="userandpost">
 By <%= link_to tutorial.user.username, tutorial.user %> <!--(Guided <b><%= tutorial.user.reputation_for(:user_votes).to_i %> coders </b>to safety)--> | <%="#{time_ago_in_words(tutorial.created_at)} ago" %> | <%= tutorial.steps.count %> steps</div>

   <!-- Tags: <% tutorial.tags.any? %>
  <% tutorial.tags.each do |tag| %>
  <%= link_to tag.name, tagged_url(:tag => tag.name) %> 
<% end %> |  Working Demo: <%= link_to tutorial.website, tutorial.website %> -->

       <% if current_user.present? && tutorial.editor?(current_user) %>
          <%= link_to "Edit", edit_tutorial_path(tutorial), :class => "btn" %>
          <%= link_to "Delete", tutorial_path(tutorial), :method => "delete", :class => "btn btn-danger" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<%= will_paginate(@tutorial, :renderer => WillPaginate::ActionView::LinkRenderer) %>
</div>
  <div class="span3">
    <div class="wellcomplete" align="center">
    <h4>About YTutorial</h4>
    We are a community of rails developers teaching each other to code. This is an <a href="https://github.com/danvoell/ytutorial">open source project on github</a>. Please help our community get smarter, make a tutorial today<br><br>  <%= link_to "Make Your Own Tutorial", new_tutorial_path, :class => "btn btn-success" %> <br><br>
    <div id="search">
          <%= form_tag tutorials_path, :method => 'get' do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil, :class => "btn btn-success" %>
         </p>
        <% end %>

    <% @searchtutorials.each do |tutorial| %>
<li><%= link_to tutorial.title, tutorial_path(tutorial) %></li>
<% end %>
      

      </div>

  </div>

<script>
  (function() {
    var cx = '011548052767392118901:qftdif1o4ai';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>

     <div class="wellcomplete" align="center">
    <h4>Additional Resources</h4><hr>
      Learn via Videos with Ryan Bates’s <a href="http://railscasts.com/">RailsCasts</a><hr>
      Learn via Tutorial with Michael Hartl's <a href="http://ruby.railstutorial.org/">RailsTutorial</a>
     </div>

       


<!-- <div class="well" align="center">
    <h3>Makers Club</h3>
    The make club chooses one tutorial/gem per week to go through. Sign Up Today!</div>
-->

  </div>
    </div>
</div>

app/views/tutorials/new.html.erb
<h1>Create A Tutorial</h1>
<%= render :partial => "form" %>
<br />
<%= link_to "Back", tutorials_path %>

app/views/tutorials/show.html.erb
<div class="row">
<!--<div class="span3"><br>
<%= image_tag @tutorial.image_url(:medium) if @tutorial.image? %>
	</div> -->  
<div class="span10">
    <h1><%= @tutorial.title %></h1>
<b>Short Description:</b> <%= @tutorial.outline.html_safe %>
<br><b>Link to Working Product:</b> <a href="<%= @tutorial.website %>"><%= @tutorial.website %></a>
<!-- <br><b>Tags:</b>

<% @tutorial.tags.any? %>
  <% @tutorial.tags.each do |tag| %>
  <%= link_to tag.name, tagged_url(:tag => tag.name) %>
<% end %> -->

<br><b>Successfully Completed By: </b><%= pluralize @tutorial.reputation_for(:votes).to_i, "folk" %><br>
<b>Tutorial By:</b> <%= link_to @tutorial.user.username, @tutorial.user %>
    

</div>


<div class="span2">
    <br>
<div class="well" align="center">
 Share Tutorial<br>
<%= link_to "http://www.facebook.com/sharer.php?u=#{tutorial_url(@tutorial)}" do %> <i class="fa fa-facebook fa-2x"></i>
<% end %>
                        

<%= link_to "http://twitter.com/home?status=YTutorial - #{@tutorial.title} #{tutorial_url(@tutorial)} " do %>
 <i class="fa fa-twitter fa-2x"></i>
<% end %>

<%= link_to "https://plus.google.com/share?url=#{tutorial_url(@tutorial)}" do %>
 <i class="fa fa-google-plus fa-2x"></i>
<% end %>         
	</div>
	
	  </div>
	
	 

</div>
<hr>    
<div class="row">
	<div class="span7">
<div class="accordion" id="steps-accordion">
      
      
      <% count = 0 %>
      <% @tutorial.steps.each do |step| %>
        <% count += 1 %>
        <div class="accordion-group" data-kind="step" data-step-count="<%= count %>" data-step-id="<%= step.id %>"> 
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#steps-accordion" href="#step-<%= step.id %>">
              Step <%= count %> - <%= step.steptitle %>
            </a>
          </div>

          <div id="step-<%= step.id %>" class="accordion-body collapse">
            <div class="accordion-inner">
              <%= step.content.html_safe %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  
  <div class="span5" data-kind="comments">
    <h3>Discuss Individual Steps</h3>
    <% @tutorial.steps.each do |step| %>
      <div data-kind="comment-block" data-comment-type="step" data-comments-step-id="<%= step.id %>">
        <%= render partial: 'comment', collection: step.comments %>
        <%= render partial: 'comment_form', object: Comment.new(step_id: step.id) %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="span6">
    <%= link_to "I Successfully Completed This Tutorial!", vote_tutorial_path(@tutorial, type: "up"), method: "post", :class => "btn btn-info" %> <br><br>
    
  </div>
</div>

app/views/tutorials/tagged.html.erb
<h3>Learn by following tutorials or <%= link_to "Make Your Own", new_tutorial_path, :class => "btn btn-success btn-large" %></h3>
<br />

<table class="table table-striped">
  <tr>
	<th>Picture</th>
	
   <th>Title</th>
	
	<th>Actions</th>
			</tr>
  


<% @tutorials.each do |tutorial| %>

    <tr>

     <td>  </td>

<td><%= image_tag tutorial.image_url(:thumb) if tutorial.image? %></td>      

<div class="details">
<td><h3><%= link_to tutorial.title, tutorial_path(tutorial) %></h3>
</div>
<p class="exc"><%= tutorial.outline.html_safe %></p>
<p class="manage">
  <a href="/resources/d3-js-basic-tutorials">0 comments</a>
   | <span class="f">1</span> Completed

</td>
      
<td> <% if current_user.present? && tutorial.editor?(current_user) %>
          <%= link_to "Edit", edit_tutorial_path(tutorial), :class => "btn" %>
          <%= link_to "Delete", tutorial_path(tutorial), :method => "delete", :class => "btn btn-danger" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/tutorials/teststyle.html.erb
	    <li class="clearfix r-tutorial " data-id="1821">
 
 <div class="details clearfix">
    <h2>
      <img alt="D3.js Basic Tutorials" class="favicon" height="16" src="http://1821.getfavicon.appspot.com/http%3A%2F%2Fwww.janwillemtulp.com%2Fcategory%2Fd3?defaulticon=lightpng" width="16" />
      <a href="http://www.janwillemtulp.com/category/d3" rel="nofollow" target="_blank">D3.js Basic Tutorials</a> / free
    </h2>
    <p class="exc">A set of introduction tutorials for D3js, including conway&#x27;s game of life.</p>
    <ul class="tags clearfix">
      <li><a href="/tags/d3-js">d3.js</a></li>
    </ul>
    <p class="manage">
      <a href="/resources/d3-js-basic-tutorials">0 comments</a>
       | <span class="f">1</span> favorite
      
    </p>
    <p class="time">about 6 hours ago, by <a href="/profiles/301">301</a></p>
  </div>
  <div class="thumb-small">                     
    <a href="http://www.janwillemtulp.com/category/d3" rel="nofollow" target="_blank"><img alt="D3.js Basic Tutorials" class="thumb" height="120" src="http://beta.url2png.com/v6/P500DA18113E7E/28b8068d2a23f8d2bccca1a179c94867/png/?url=http%3A%2F%2Fwww.janwillemtulp.com%2Fcategory%2Fd3&amp;fullpage=false&amp;thumbnail_max_width=250&amp;viewport=1000x800" width="150" /></a>
		<div class='sprite ribbon'>popular tutorial</div>
  </div>
</li>